### ISSUE TITLE
Nothing returned from the server when querying UTxOs

### ISSUE THREAD

**Issue by MartinSchere** [CardanoSolutions/kupo#47] opened 2022-07-24 22:41 UTC
#### What Git revision are you using? 
v1.0.1 

#### What operating system are you using, and which version?

- [ x] Linux / Ubuntu
- [ ] Linux / Other
- [ ] OSX
- [ ] Windows

#### Describe what the problem is? 

When querying the following asset:

`http://localhost:1442/v1/matches/addr1zxj47sy4qxlktqzmkrw8dahe46gtv8seakrshsqz26qnvzypw288a4x0xf8pxgcntelxmyclq83s0ykeehchz2wtspksr3q9nx?unspent&policy_id=d7726f6b882c6fc2ca0cd96c51e5328e1d577d789b085ee0fbe23bf7&asset_name=55676c7942726f546865446566696e697469766536393439`

I get:

`curl: (52) Empty reply from server`

#### What should be the expected behavior?

Getting the UTxOs for the asset.

### ---

Could it be because of the asset length? Maybe there's some truncating going on

**Comment by KtorZ** [comment] 2022-07-25 05:30
Hey @MartinSchere, this feature will only be available in v2.0.0 which is in the making. I've been delaying a bit the release until the next version of Cardano-node gets out.

However, this should already work from the latest master.

**Comment by MartinSchere** [comment] 2022-07-25 15:19
@KtorZ thank you for your reply.

We are getting successful reponses 95% of the time, it's with this specific asset that we're getting an empty response. I mistakenly wrote 1.0.1 as our git revision, it's rather the latest docker image. Could you try it out locally? What response do you get?

**Comment by KtorZ** [comment] 2022-07-25 15:51
I don't have a mainnet index synchronized locally, at least, not with the v2.0.0 table scheme. I'll later this week as I am wrapping up benchmarks & al for the release. 

If I still run the query on a non-synchronized local instance however, I get an empty array `[]` :thinking: 

```
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Mon, 25 Jul 2022 15:49:18 GMT
< Server: kupo
< X-Most-Recent-Checkpoint: 41276179
< Content-Type: application/json;charset=utf-8
< 
[]
```

**Comment by KtorZ** [comment] 2022-08-05 13:36
@MartinSchere I am unable to reproduce this.

I don't know what happened on the build / version you got. A lot happened on `master` and while I try to keep the main branch stable, I sometime introduce small breakages during the course of development (with the goal to produce stable releases however). 

I've actually added your query to the query bench, see [benchmarks/README.md#query](https://github.com/CardanoSolutions/kupo/tree/master/benchmarks#query). On current mainnet, the query returns a list of one element:

```json
[
  {
    "transaction_id": "ca7ddc83957d17c8435aab5c7ef453d5a0fa9554485c0613ac3988dc921b94f3",
    "output_index": 0,
    "address": "addr1zxj47sy4qxlktqzmkrw8dahe46gtv8seakrshsqz26qnvzypw288a4x0xf8pxgcntelxmyclq83s0ykeehchz2wtspksr3q9nx",
    "value": {
      "coins": 1758582,
      "assets": {
        "d7726f6b882c6fc2ca0cd96c51e5328e1d577d789b085ee0fbe23bf7.55676c7942726f546865446566696e697469766536393439": 1
      }
    },
    "datum_hash": "58a01b3bbdbdaad2c776a079a002b30241b79f2b79e39ea6efd1487fdca9d3e9",
    "script_hash": null,
    "created_at": {
      "slot_no": 65737064,
      "header_hash": "0aec072001e10da7051e6cfd27933612cd0fbcead0d421c3f334f10be932f860"
    },
    "spent_at": null
  }
]
```

Therefore closing this, but happy to re-investigate if you bump into this again?

**Closed by KtorZ** 2022-08-05 13:36 UTC

**Comment by MartinSchere** [comment] 2022-08-07 17:12
@KtorZ Sure, thanks for your help.

jpg.store is proudly using Kupo right now :)
