### ISSUE TITLE
UTxO paging

### ISSUE THREAD

**Issue by szist** [CardanoSolutions/kupo#76] opened 2022-10-18 11:20 UTC
#### Describe your idea, in simple words.
Since some addresses might a lot of spent utxo history, it would be good to have the ability to use at least limit, offset paging.

#### Why is it a good idea?
It would allow showing a transaction history in the UI for a given address without fetching all spent txos.
Secondary use-case might be to check if a given address is used - by limiting the number of results to 1 would allow more easily to detect if an address is used. But for that a different proposal could be more useful.

This would also help with the data usage that is sent to the clients.

#### Are you willing to work on it yourself?
Maybe, but I'm not as fluent in haskell.

**Comment by KtorZ** [comment] 2022-10-18 11:24
Hey! Thanks for reaching out. Closing this as it is a duplicate of https://github.com/CardanoSolutions/kupo/discussions/75. 

We'll continue the discussion there and I'll provide an update on this very soon.

**Closed by KtorZ** 2022-10-18 11:24 UTC
