### ISSUE TITLE
kupo V2.0.0 api queries faster than V2.4.0

### ISSUE THREAD

**Issue by cybershaman73** [CardanoSolutions/kupo#119] opened 2023-04-22 21:31 UTC
### What Git revision / release tag are you using?
2.4.0

### Describe what the problem is?
Local socket api queries to V2.4.0 are slower than V2.0.0 with the same configuration. 
Example config:
--node-socket ${socket} \
--node-config ${config} \
--log-level ${loglevel} \
--prune-utxo \
--since ${since} \
--match ${match} \
--workdir ${workdir}

### What should be the expected behavior?
Expected behavior is no change in speed or faster.

**Comment by KtorZ** [comment] 2023-08-16 07:03
Closing this ticket for the following reasons:

- Unable to reproduce neither from v2.4.0 or v2.5.0, despite multiple benchmarks rounds on different machines. 
- Lack of data points to actually evaluate this scenario
- More logs have been added (between v2.5.0 and in the upcoming v2.6.0) which should help troubleshoot similar cases in the future.

**Closed by KtorZ** 2023-08-16 07:03 UTC
Labels: Performances / optimizations
